import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1773489758128 implements MigrationInterface {
    name = 'InitialSchema1773489758128'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pg_trgm"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "phone" character varying(20) NOT NULL, "passwordHash" character varying(255) NOT NULL, "nickname" character varying(50) NOT NULL, "avatarUrl" character varying(500), "status" character varying(20) NOT NULL DEFAULT 'active', "lastLoginAt" TIMESTAMP, CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_status" ON "users" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`CREATE TABLE "style_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "traits" jsonb NOT NULL DEFAULT '{}', "vectorCollection" character varying(100), "sampleCount" integer NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'draft', "user_id" uuid, CONSTRAINT "PK_2cc9e98614f760cec72d2821379" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_style_profiles_user_status" ON "style_profiles" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_style_profiles_status" ON "style_profiles" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_style_profiles_user_id" ON "style_profiles" ("userId") `);
        await queryRunner.query(`CREATE TABLE "scene_modes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "name" character varying(100) NOT NULL, "description" text, "replyStyle" character varying(30) NOT NULL DEFAULT 'casual', "autoReply" boolean NOT NULL DEFAULT true, "isActive" boolean NOT NULL DEFAULT false, "rules" jsonb NOT NULL DEFAULT '{}', "profileId" uuid, "sortOrder" integer NOT NULL DEFAULT '0', "user_id" uuid, "profile_id" uuid, CONSTRAINT "PK_9100732daac69462e84dafe9608" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_scene_modes_user_active" ON "scene_modes" ("userId", "isActive") `);
        await queryRunner.query(`CREATE INDEX "idx_scene_modes_user_id" ON "scene_modes" ("userId") `);
        await queryRunner.query(`CREATE TABLE "user_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "defaultSceneId" uuid, "defaultProfileId" uuid, "autoReply" boolean NOT NULL DEFAULT true, "notificationEnabled" boolean NOT NULL DEFAULT true, "reviewTimeout" integer NOT NULL DEFAULT '300', "language" character varying(10) NOT NULL DEFAULT 'zh-CN', "user_id" uuid, "default_scene_id" uuid, "default_profile_id" uuid, CONSTRAINT "UQ_986a2b6d3c05eb4091bb8066f78" UNIQUE ("userId"), CONSTRAINT "PK_00f004f5922a0744d174530d639" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_user_settings_user_id" ON "user_settings" ("userId") `);
        await queryRunner.query(`CREATE TABLE "file_uploads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "fileName" character varying(255) NOT NULL, "fileKey" character varying(500) NOT NULL, "fileSize" bigint NOT NULL, "mimeType" character varying(100) NOT NULL, "purpose" character varying(30) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'uploaded', "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_b3ebfc99a8b660f0bc64a052b42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_file_uploads_expires" ON "file_uploads" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "idx_file_uploads_status" ON "file_uploads" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_file_uploads_user_id" ON "file_uploads" ("userId") `);
        await queryRunner.query(`CREATE TABLE "style_tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "profileId" uuid, "fileId" uuid, "status" character varying(20) NOT NULL DEFAULT 'pending', "progress" integer NOT NULL DEFAULT '0', "errorMessage" text, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "profile_id" uuid, "file_id" uuid, CONSTRAINT "PK_d504fb4541d26b193abb05963aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_style_tasks_status" ON "style_tasks" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_style_tasks_user_id" ON "style_tasks" ("userId") `);
        await queryRunner.query(`CREATE TABLE "style_samples" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profileId" uuid NOT NULL, "content" text NOT NULL, "platform" character varying(30) NOT NULL, "role" character varying(20) NOT NULL DEFAULT 'user', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "profile_id" uuid, CONSTRAINT "PK_cc23638017fea69dbd63ad46a71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_style_samples_platform" ON "style_samples" ("platform") `);
        await queryRunner.query(`CREATE INDEX "idx_style_samples_profile_id" ON "style_samples" ("profileId") `);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "platformId" character varying(100) NOT NULL, "platform" character varying(30) NOT NULL, "nickname" character varying(100) NOT NULL, "remark" character varying(100), "avatar" character varying(500), "level" character varying(20) NOT NULL DEFAULT 'normal', "isWhitelist" boolean NOT NULL DEFAULT false, "isBlacklist" boolean NOT NULL DEFAULT false, "tags" jsonb NOT NULL DEFAULT '[]', "customReplyProfileId" uuid, "notes" text, "messageCount" integer NOT NULL DEFAULT '0', "lastMessageAt" TIMESTAMP, "user_id" uuid, "custom_reply_profile_id" uuid, CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_contacts_blacklist" ON "contacts" ("userId", "isBlacklist") `);
        await queryRunner.query(`CREATE INDEX "idx_contacts_whitelist" ON "contacts" ("userId", "isWhitelist") `);
        await queryRunner.query(`CREATE INDEX "idx_contacts_level" ON "contacts" ("userId", "level") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_contacts_platform_id" ON "contacts" ("userId", "platformId", "platform") `);
        await queryRunner.query(`CREATE INDEX "idx_contacts_user_platform" ON "contacts" ("userId", "platform") `);
        await queryRunner.query(`CREATE INDEX "idx_contacts_user_id" ON "contacts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_contacts_nickname" ON "contacts" USING GIN ("nickname" gin_trgm_ops)`);
        await queryRunner.query(`CREATE TABLE "reply_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "contactId" uuid NOT NULL, "profileId" uuid, "sceneId" uuid, "incomingMessageId" uuid, "incomingContent" text NOT NULL, "candidates" jsonb NOT NULL DEFAULT '[]', "selectedIndex" integer, "sentContent" text, "status" character varying(20) NOT NULL DEFAULT 'pending', "feedbackRating" integer, "feedbackTag" character varying(30), "feedbackComment" text, "reviewedAt" TIMESTAMP, "sentAt" TIMESTAMP, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "contact_id" uuid, "profile_id" uuid, "scene_id" uuid, "incoming_message_id" uuid, CONSTRAINT "PK_a23a631b76fcd81d3393f51b1ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_reply_records_expires" ON "reply_records" ("status", "expiresAt") `);
        await queryRunner.query(`CREATE INDEX "idx_reply_records_created" ON "reply_records" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_reply_records_contact" ON "reply_records" ("userId", "contactId") `);
        await queryRunner.query(`CREATE INDEX "idx_reply_records_status" ON "reply_records" ("userId", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_reply_records_user_id" ON "reply_records" ("userId") `);
        await queryRunner.query(`CREATE TABLE "platform_auths" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "platform" character varying(30) NOT NULL, "accountNickname" character varying(100), "accountAvatar" character varying(500), "accessToken" text NOT NULL, "refreshToken" text, "tokenExpiresAt" TIMESTAMP, "status" character varying(20) NOT NULL DEFAULT 'connected', "config" jsonb NOT NULL DEFAULT '{}', "lastActiveAt" TIMESTAMP, "user_id" uuid, CONSTRAINT "PK_de3983270e9fd36ffa021593cce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_platform_auths_status" ON "platform_auths" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_platform_auths_user_platform" ON "platform_auths" ("userId", "platform") `);
        await queryRunner.query(`CREATE INDEX "idx_platform_auths_user_id" ON "platform_auths" ("userId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "type" character varying(30) NOT NULL, "title" character varying(200) NOT NULL, "content" text NOT NULL, "actionUrl" character varying(500), "isRead" boolean NOT NULL DEFAULT false, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_created" ON "notifications" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_unread" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_id" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "contactId" uuid, "direction" character varying(10) NOT NULL, "content" text NOT NULL, "msgType" character varying(20) NOT NULL DEFAULT 'text', "platform" character varying(30) NOT NULL, "platformMsgId" character varying(200), "isAiGenerated" boolean NOT NULL DEFAULT false, "replyRecordId" uuid, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, "contact_id" uuid, "reply_record_id" uuid, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_messages_platform_msg_id" ON "messages" ("platformMsgId") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_contact_created" ON "messages" ("userId", "contactId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_direction" ON "messages" ("userId", "direction") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_platform" ON "messages" ("userId", "platform") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_user_created" ON "messages" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_contact_id" ON "messages" ("userId", "contactId") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_user_id" ON "messages" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_messages_content_search" ON "messages" USING GIN (to_tsvector('simple', "content"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "action" character varying(50) NOT NULL, "resourceType" character varying(50) NOT NULL, "resourceId" uuid, "details" jsonb, "ipAddress" character varying(45), "userAgent" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "user_id" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_created" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_resource" ON "audit_logs" ("resourceType", "resourceId") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user_id" ON "audit_logs" ("userId") `);
        await queryRunner.query(`ALTER TABLE "style_profiles" ADD CONSTRAINT "FK_14cfb12bce51fa80a2e0130646e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "scene_modes" ADD CONSTRAINT "FK_0fa5ef3bba92f20f4fbb3e9c30c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "scene_modes" ADD CONSTRAINT "FK_1448ceed7fa23a3d432aa3a93c5" FOREIGN KEY ("profile_id") REFERENCES "style_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_53d99c12882a2f8c5aea810c96c" FOREIGN KEY ("default_scene_id") REFERENCES "scene_modes"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_settings" ADD CONSTRAINT "FK_06618a624a81870080b0598ed07" FOREIGN KEY ("default_profile_id") REFERENCES "style_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "file_uploads" ADD CONSTRAINT "FK_e98a66989ce33c0f7343bc502dd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "style_tasks" ADD CONSTRAINT "FK_b5689f60ba5518228b077f32c09" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "style_tasks" ADD CONSTRAINT "FK_6c38718a6ad17120a38901c3b80" FOREIGN KEY ("profile_id") REFERENCES "style_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "style_tasks" ADD CONSTRAINT "FK_b973290d0f37454bc3203bfc9a8" FOREIGN KEY ("file_id") REFERENCES "file_uploads"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "style_samples" ADD CONSTRAINT "FK_144095b135562124c3a5b0575ab" FOREIGN KEY ("profile_id") REFERENCES "style_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_af0a71ac1879b584f255c49c99a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_1b65d234ad8c47e97bdeea313b6" FOREIGN KEY ("custom_reply_profile_id") REFERENCES "style_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_records" ADD CONSTRAINT "FK_c2ebcb92cc444c2bbf59bace31a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_records" ADD CONSTRAINT "FK_bc06d8a06187b44999fae5cfd9d" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_records" ADD CONSTRAINT "FK_41d123a7bd0fb0ccd8d80a01128" FOREIGN KEY ("profile_id") REFERENCES "style_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_records" ADD CONSTRAINT "FK_162081871566eaae2aba41729cb" FOREIGN KEY ("scene_id") REFERENCES "scene_modes"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reply_records" ADD CONSTRAINT "FK_d6ad7cd3819395f90b5eef23721" FOREIGN KEY ("incoming_message_id") REFERENCES "messages"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "platform_auths" ADD CONSTRAINT "FK_a102149867053cf8e5d63fffaf5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_830a3c1d92614d1495418c46736" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_d109211ed510ef10617c5e75927" FOREIGN KEY ("contact_id") REFERENCES "contacts"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_15e42f328848163b797cb04b02e" FOREIGN KEY ("reply_record_id") REFERENCES "reply_records"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_15e42f328848163b797cb04b02e"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_d109211ed510ef10617c5e75927"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_830a3c1d92614d1495418c46736"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "platform_auths" DROP CONSTRAINT "FK_a102149867053cf8e5d63fffaf5"`);
        await queryRunner.query(`ALTER TABLE "reply_records" DROP CONSTRAINT "FK_d6ad7cd3819395f90b5eef23721"`);
        await queryRunner.query(`ALTER TABLE "reply_records" DROP CONSTRAINT "FK_162081871566eaae2aba41729cb"`);
        await queryRunner.query(`ALTER TABLE "reply_records" DROP CONSTRAINT "FK_41d123a7bd0fb0ccd8d80a01128"`);
        await queryRunner.query(`ALTER TABLE "reply_records" DROP CONSTRAINT "FK_bc06d8a06187b44999fae5cfd9d"`);
        await queryRunner.query(`ALTER TABLE "reply_records" DROP CONSTRAINT "FK_c2ebcb92cc444c2bbf59bace31a"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_1b65d234ad8c47e97bdeea313b6"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_af0a71ac1879b584f255c49c99a"`);
        await queryRunner.query(`ALTER TABLE "style_samples" DROP CONSTRAINT "FK_144095b135562124c3a5b0575ab"`);
        await queryRunner.query(`ALTER TABLE "style_tasks" DROP CONSTRAINT "FK_b973290d0f37454bc3203bfc9a8"`);
        await queryRunner.query(`ALTER TABLE "style_tasks" DROP CONSTRAINT "FK_6c38718a6ad17120a38901c3b80"`);
        await queryRunner.query(`ALTER TABLE "style_tasks" DROP CONSTRAINT "FK_b5689f60ba5518228b077f32c09"`);
        await queryRunner.query(`ALTER TABLE "file_uploads" DROP CONSTRAINT "FK_e98a66989ce33c0f7343bc502dd"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_06618a624a81870080b0598ed07"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_53d99c12882a2f8c5aea810c96c"`);
        await queryRunner.query(`ALTER TABLE "user_settings" DROP CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302"`);
        await queryRunner.query(`ALTER TABLE "scene_modes" DROP CONSTRAINT "FK_1448ceed7fa23a3d432aa3a93c5"`);
        await queryRunner.query(`ALTER TABLE "scene_modes" DROP CONSTRAINT "FK_0fa5ef3bba92f20f4fbb3e9c30c"`);
        await queryRunner.query(`ALTER TABLE "style_profiles" DROP CONSTRAINT "FK_14cfb12bce51fa80a2e0130646e"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_resource"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_created"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_content_search"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_contact_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_user_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_platform"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_direction"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_contact_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_platform_msg_id"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_unread"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_created"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."idx_platform_auths_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_platform_auths_user_platform"`);
        await queryRunner.query(`DROP INDEX "public"."idx_platform_auths_status"`);
        await queryRunner.query(`DROP TABLE "platform_auths"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reply_records_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reply_records_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reply_records_contact"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reply_records_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reply_records_expires"`);
        await queryRunner.query(`DROP TABLE "reply_records"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contacts_nickname"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contacts_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contacts_user_platform"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contacts_platform_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contacts_level"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contacts_whitelist"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contacts_blacklist"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_samples_profile_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_samples_platform"`);
        await queryRunner.query(`DROP TABLE "style_samples"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_tasks_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_tasks_status"`);
        await queryRunner.query(`DROP TABLE "style_tasks"`);
        await queryRunner.query(`DROP INDEX "public"."idx_file_uploads_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_file_uploads_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_file_uploads_expires"`);
        await queryRunner.query(`DROP TABLE "file_uploads"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_settings_user_id"`);
        await queryRunner.query(`DROP TABLE "user_settings"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scene_modes_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_scene_modes_user_active"`);
        await queryRunner.query(`DROP TABLE "scene_modes"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_profiles_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_profiles_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_style_profiles_user_status"`);
        await queryRunner.query(`DROP TABLE "style_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_status"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
